title: "イベントループとプロミスチェーンで学ぶJavaScriptの非同期処理"
summary: "JavaScript の非同期処理は非常に難しく、学習そのものにハードルがあります。
\n\n
そして、難しさの本質は「制御の流れ」が掴みづらいことにあります。
\n\n
この本では非同期処理の理解するために必要な概念であり仕組みでもある Event loop において Promise chain の処理がどのように動くかを実際にクイズ形式で学ぶことによって非同期処理の「制御の流れ」を掴めるように訓練します。
\n\n
本としての体裁は取っていますが、自分自身のアウトプットを兼ねているため、この本は無料公開となっています。現時点で内容としては未完成なので、頻繁に追記修正がある点に注意してください。
"
topics: ["JavaScript", "非同期処理", "Promise"]
published: true
price: 0
chapters:
  - 1-epasync-begin
  - 2-epasync-event-loop
  - a-epasync-promise-basic-consept
  - 3-epasync-promise-constructor-executor-func
  - 4-epasync-callback-is-sync-or-async
  - 5-epasync-multiple-promises
  - 6-epasync-then-always-return-new-promise
  - 7-epasync-pass-value-to-the-next-chain
  - 8-epasync-return-promise-in-then-callback
  - 9-epasync-dont-next-promise-chain
  - 10-epasync-dont-use-side-effect
  - 11-epasync-omit-return-by-arrow-shortcut
  - 12-epasync-wrapping-macrotask
  - 13-epasync-loop-is-nested

