title: "イベントループとプロミスチェーンで学ぶJavaScriptの非同期処理"
summary: "JavaScript の非同期処理は非常に難しく、学習そのものにハードルがあります。そして、難しさの本質は「制御の流れ」が掴みづらいことにあります。
\n\n
この本では、非同期処理を理解するために必要な概念であり、仕組みでもあるイベントループにおいて Promise チェーンの処理がどのように動くかをクイズ形式で学ぶことによって、非同期処理の「制御の流れ」を掴めるように訓練します。
\n\n
知識面については、非同期 API とイベントループの理解から始め、Promise の基礎的概念から Promise チェーンへと続き、最終的にはそこまでのすべての知識と V8 エンジンからのアプローチによって async/await の挙動を理解します。
"
topics: ["JavaScript", "Node", "Deno", "非同期処理", "Promise"]
published: true
price: 0
chapters:
  - 1-epasync-begin # はじめに
  - sec-01-epasync # 第１章
  - f-epasync-asyncronous-apis # 非同期 API と環境
  - f-epasync-synchronus-apis # 同期 API とブロッキング
  - 2-epasync-event-loop # イベントループの概要と注意点
  - d-epasync-task-microtask-queues # タスクキューとマイクロタスクキュー
  - e-epasync-v8-engine # V8エンジン
  - b-epasync-callstack-execution-context #コールスタックと実行コンテキスト
  - c-epasync-what-event-loop # それぞれのイベントループ
  - sec-02-epasync # 第２章
  - a-epasync-promise-basic-consept # Promise の基本概念
  - 3-epasync-promise-constructor-executor-func # Promise コンストラクタと Executor 関数
  - 4-epasync-callback-is-sync-or-async # コールバック関数の同期実行と非同期実行
  - g-epasync-resolve-reject # resolve 関数と reject 関数の使い方
  - 5-epasync-multiple-promises # 複数の Promise を走らせる
  - 6-epasync-then-always-return-new-promise # then メソッドは常に新しい Promise を返す
  - 7-epasync-pass-value-to-the-next-chain # Promise チェーンで値を繋ぐ
  - 8-epasync-return-promise-in-then-callback # then メソッドのコールバックで Promise インスタンスを返す
  - 9-epasync-dont-next-promise-chain # Promise チェーンはネストさせない
  - 10-epasync-dont-use-side-effect # then メソッドのコールバックで非同期処理
  - 11-epasync-omit-return-by-arrow-shortcut # アロー関数で return を省略する
  - h-epasync-catch-finally # catch メソッドと finally メソッド
  - 12-epasync-wrapping-macrotask # 古い非同期APIをPromiseでラップする
  - 13-epasync-loop-is-nested # イベントループは内部にネストしたループがある
  - sec-03-epasync # 第３章
  - 14-epasync-chain-to-async-await # Promise チェーンから非同期関数へ
  - 15-epasync-v8-converting # V8 エンジンによる async/await の内部変換
  - 16-epasync-top-level-async # Top-level await
  - x-epasync-epilogue # あとがき

