title: "イベントループとプロミスチェーンで学ぶJavaScriptの非同期処理"
summary: "JavaScript の非同期処理は非常に難しく、学習そのものにハードルがあります。
\n\n
そして、難しさの本質は「制御の流れ」が掴みづらいことにあります。
\n\n
この本では非同期処理の理解するために必用な概念(仕組み)である Event loop において Promise chain の処理がどのように動くかを実際にクイズ形式で学ぶことによって JavaScript の非同期処理における「制御の流れ」を掴めるようになるためのポイントを解説します。
\n\n
本としての体裁は撮っていますが、自分自身のアウトプットを兼ねているため、この本は無料公開となっています。現時点で内容としては未完成なので、頻繁に追記修正がある点に注意してください。
"
topics: ["JavaScript", "非同期処理", "Promise"]
published: true
price: 0
