title: "イベントループとプロミスチェーンで学ぶJavaScriptの非同期処理"
summary: "JavaScript の非同期処理は非常に難しく、学習そのものにハードルがあります。
\n\n
そして、難しさの本質は「制御の流れ」が掴みづらいことにあります。
\n\n
この本では非同期処理の理解するために必要な概念であり仕組みでもある Event loop において Promise chain の処理がどのように動くかを実際にクイズ形式で学ぶことによって非同期処理の「制御の流れ」を掴めるように訓練します。
\n\n
本としての体裁は取っていますが、自分自身のアウトプットを兼ねているため、この本は無料公開となっています。現時点で内容としては未完成なので、頻繁に追記修正がある点に注意してください。
"
topics: ["JavaScript", "Node", "Deno", "非同期処理", "Promise"]
published: true
price: 0
chapters:
  - 1-epasync-begin # はじめに
  - f-epasync-asyncronous-apis # 非同期APIと環境
  - 2-epasync-event-loop # イベントループの概要と注意点
  - d-epasync-task-microtask-queues # タスクキューとマイクロタスクキュー
  - e-epasync-v8-engine # V8エンジン
  - b-epasync-callstack-execution-context #コールスタックと実行コンテキスト
  - c-epasync-what-event-loop # それぞれのイベントループ
  - a-epasync-promise-basic-consept # Promise の基本概念
  - 3-epasync-promise-constructor-executor-func # Promise コンストラクタと Executor 関数
  - 4-epasync-callback-is-sync-or-async # コールバック関数の同期実行と非同期実行
  - g-epasync-resolve-reject # resolve と reject の使い方
  - h-epasync-catch-finally # catch メソッドと finally メソッド
  - 5-epasync-multiple-promises # 複数の Promise を走らせる
  - 6-epasync-then-always-return-new-promise # then メソッドは常に新しい Promise を返す
  - 7-epasync-pass-value-to-the-next-chain # Promise チェーンで値を繋ぐ
  - 8-epasync-return-promise-in-then-callback # thenコールバックでPromiseインスタンスを返す
  - 9-epasync-dont-next-promise-chain # Promise チェーンはネストさせない
  - 10-epasync-dont-use-side-effect # then メソッドのコールバックで非同期処理
  - 11-epasync-omit-return-by-arrow-shortcut # アロー関数で return を省略する
  - 12-epasync-wrapping-macrotask # 古い非同期APIをPromiseでラップする
  - 13-epasync-loop-is-nested # イベントループは内部にネストしたループがある
  - 14-epasync-chain-to-async-await # Promise チェーンから非同期関数へ
  - 15-epasync-v8-converting # V8 エンジンによる async/await の内部変換

