title: "Obsidian.Zenn"
summary: "次世代のノートテーキングツールである Obsidian を使って Zenn で記事や本を作ろう!
"
topics: ["Obsidian", "Zenn", "Markdown", "vscode", "Blog"]
published: true
price: 0
chapters:
  - 1-oz-begin # [[1-oz-begin|OZ本『はじめに』]]
  - 2-oz-what-is-obsidian # [[2-oz-what-is-obsidian|OZ本『Obsidian とは』]]
  - 3-oz-thinking-way # [[3-oz-thinking-way|OZ本『Obsidian の考え方』]]
  - 4-oz-make-zenn-repo # [[4-oz-make-zenn-repo|OZ本『保管庫と Zenn リポジトリの作成』]]
  - a-oz-add-plugins # [[a-oz-add-plugins|OZ本『プラグインを導入しよう』]]
  - 5-oz-make-article-book # [[5-oz-make-article-book|OZ本『記事や本を作成しよう』]]
  - 6-oz-reuse-memo # [[6-oz-reuse-memo|OZ本『情報を再利用しよう』]]
  - b-oz-css-snippets # [[b-oz-css-snippets|OZ本『カスタム CSS スニペットでデザインしよう』]]

